---
- name: Converge
  hosts: all
  gather_facts: false
#  vars:
#    #keepass_dbx: './default/resources/keepass.kdbx'
#    keepass_dbx: "/keepass.kdbx"
#    #keepass_dbx: "${MOLECULE_PROJECT_DIRECTORY}/molecule/default/resources/ansible_keepass.kdbx"
#    #keepass_dbx: '../../../../../../../../workspaces/ansible-keepass/molecule/default/resources/keepass.kdbx'
#    keepass_psw: 'test_password'
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"

#    - name: Find out playbooks path
#      shell: pwd
#      register: playbook_path_output
#    - debug: var=playbook_path_output.stdout
#
#    - name: Find out playbooks path
#      shell: echo "${MOLECULE_PROJECT_DIRECTORY}"
#      register: playbook_path_output2
#    - debug: var=playbook_path_output2.stdout
#    - name: test1
#      ansible.builtin.debug:
#        msg: "{{ lookup('hczv.keepass.lookup', 'username') }}"
#    - name: test1
#      ansible.builtin.debug:
#        msg: "{{ lookup('hczv.keepass.lookup', 'password') }}"

