dependency:
  name: galaxy
scenario:
  name: default
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    converge: ../../tests/integration/prompt_keepass_test.yml
  config_options:
    defaults:
      vars_plugins: ${MOLECULE_PROJECT_DIRECTORY}/plugins/vars
  env:
    ANSIBLE_VERBOSITY: 2
    MOLECULE_SCENARIO: True
verifier:
  name: ansible
