---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/yaml-lint.yml .
  ansible-lint -c molecule/ansible-lint.yml .
platforms:
  - name: instance
    image: geerlingguy/docker-debian12-ansible:latest
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/resources/ansible_keepass.kdbx:/keepass.kdbx
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
provisioner:
  name: ansible
  # env:
  #   ANSIBLE_VERBOSITY: 4
  playbooks:
    converge: playbook.yml
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - create
    - prepare
    - converge
    - destroy
