dependency:
  name: galaxy
scenario:
  name: default
driver:
  name: default
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    converge: ../../tests/integration/prompt_keepass_test.yml
  config_options:
    defaults:
      vars_plugins: /workspaces/ansible-keepass/collections/ansible_collections/hczv/keepass/plugins/vars
verifier:
  name: ansible
