scenario:
  name: default
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu1804-ansible:latest"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ../../tests/integration/targets/my_vars_test/tasks/main.yml
verifier:
  name: ansible
