---
- name: Test Ansible Lookup Plugin and Module
  hosts: all
  vars:
    keepass_dbx: "/keepass.kdbx"
    keepass_psw: 'test_password'
  tasks:
    - name: Verify keepass.kdbx file exists
      ansible.builtin.stat:
        path: "{{ keepass_dbx }}"
      register: keepass_dbx_stat

    - name: Debug keepass.kdbx file stats
      ansible.builtin.debug:
        var: keepass_dbx_stat

    - name: Fail if keepass.kdbx file does not exist
      ansible.builtin.fail:
        msg: "The keepass.kdbx file does not exist at {{ keepass_dbx }}"
      when: not keepass_dbx_stat.stat.exists

    - name: Use custom lookup plugin
      ansible.builtin.debug:
        msg: "{{ lookup('hczv.keepass.lookup', 'username', keepass_dbx, keepass_psw) }}"
      when: keepass_dbx_stat.stat.exists

    - name: Use custom module
      your_custom_module:
        parameter: "{{ keepass_dbx }}"
      when: keepass_dbx_stat.stat.exists

#    - name: test1
#      ansible.builtin.debug:
#        msg: "{{ lookup('hczv.keepass.lookup', 'username') }}"
#    - name: test2
#      ansible.builtin.debug:
#        msg: "{{ lookup('hczv.keepass.lookup', 'password') }}"
